spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product-service # this field can be anything as long as it is unique
          uri: http://localhost:8081
          predicates: # it is like the condition which is validated against incoming requests
            - Path=/api/v1/products/**

        - id: user-service # this field can be anything as long as it is unique
          uri: http://localhost:8082
          predicates: # it is like the condition which is validated against incoming requests
            - Path=/api/v1/users/**

        - id: order-service # this field can be anything as long as it is unique
          uri: http://localhost:8083
          predicates: # it is like the condition which is validated against incoming requests
            - Path=/api/v1/orders/**, /api/v1/cart/**

server:
  port: 8080

